/**
 * M2 错误码枚举。
 *
 * 命名规范：`<DOMAIN>_<SPECIFIC_REASON>`
 * - DOMAIN：SYSTEM / AUTH / PERMISSION / TENANT / VALIDATION / RATE_LIMIT / NOT_FOUND / CONFLICT / QUOTA / QUEUE
 * - 业务 domain（ORDER / PAYMENT / SHIPPING 等）由业务 shared-* 或 apps/server 各自扩展
 *
 * 4 语言翻译契约：每个 code 必须在 i18n-file/messages/{zh-CN,en-US,zh-TW,ja-JP}.json 有对应翻译键
 * （shared-i18n 启动时校验，缺译 fail-fast）。
 */
export enum ErrorCode {
  // ===== SYSTEM =====
  SYSTEM_UNKNOWN = 'SYSTEM_UNKNOWN',
  SYSTEM_INTERNAL_ERROR = 'SYSTEM_INTERNAL_ERROR',
  SYSTEM_MAINTENANCE = 'SYSTEM_MAINTENANCE',
  SYSTEM_CONFIG_INVALID = 'SYSTEM_CONFIG_INVALID',
  SYSTEM_DB_CONNECTION_FAILED = 'SYSTEM_DB_CONNECTION_FAILED',
  SYSTEM_REDIS_CONNECTION_FAILED = 'SYSTEM_REDIS_CONNECTION_FAILED',
  SYSTEM_DEPENDENCY_TIMEOUT = 'SYSTEM_DEPENDENCY_TIMEOUT',

  // ===== AUTH（401 族） =====
  AUTH_UNAUTHENTICATED = 'AUTH_UNAUTHENTICATED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REVOKED = 'AUTH_TOKEN_REVOKED',
  AUTH_OTP_EXPIRED = 'AUTH_OTP_EXPIRED',
  AUTH_OTP_INVALID = 'AUTH_OTP_INVALID',
  AUTH_OTP_RATE_LIMITED = 'AUTH_OTP_RATE_LIMITED',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_MAGIC_LINK_EXPIRED = 'AUTH_MAGIC_LINK_EXPIRED',
  AUTH_MAGIC_LINK_INVALID = 'AUTH_MAGIC_LINK_INVALID',
  AUTH_SESSION_INVALID = 'AUTH_SESSION_INVALID',

  // ===== PERMISSION（403 族） =====
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  PERMISSION_SCOPE_INSUFFICIENT = 'PERMISSION_SCOPE_INSUFFICIENT',

  // ===== TENANT =====
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',
  TENANT_INACTIVE = 'TENANT_INACTIVE',
  TENANT_QUOTA_EXCEEDED = 'TENANT_QUOTA_EXCEEDED',
  TENANT_ISOLATION_VIOLATION = 'TENANT_ISOLATION_VIOLATION',

  // ===== VALIDATION =====
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  VALIDATION_MISSING_FIELD = 'VALIDATION_MISSING_FIELD',
  VALIDATION_INVALID_FORMAT = 'VALIDATION_INVALID_FORMAT',

  // ===== RATE LIMIT =====
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // ===== RESOURCE =====
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  DUPLICATE_KEY = 'DUPLICATE_KEY',
  RESOURCE_LOCKED = 'RESOURCE_LOCKED',
  RESOURCE_STATE_INVALID = 'RESOURCE_STATE_INVALID',

  // ===== QUEUE / JOB =====
  QUEUE_JOB_FAILED = 'QUEUE_JOB_FAILED',
  QUEUE_JOB_TIMEOUT = 'QUEUE_JOB_TIMEOUT',
  QUEUE_DEAD_LETTER = 'QUEUE_DEAD_LETTER',

  // ===== IDEMPOTENCY =====
  IDEMPOTENCY_IN_FLIGHT = 'IDEMPOTENCY_IN_FLIGHT',
  IDEMPOTENCY_KEY_INVALID = 'IDEMPOTENCY_KEY_INVALID',
}

/**
 * 错误码前缀 → 业务域（用于 alert rule 路由、日志分类、前端 error type 推断）。
 */
export const ERROR_CODE_DOMAINS = [
  'SYSTEM',
  'AUTH',
  'PERMISSION',
  'TENANT',
  'VALIDATION',
  'RATE_LIMIT',
  'NOT_FOUND',
  'CONFLICT',
  'DUPLICATE_KEY',
  'RESOURCE',
  'QUEUE',
  'IDEMPOTENCY',
] as const;

export type ErrorCodeDomain = (typeof ERROR_CODE_DOMAINS)[number];

/**
 * 从 ErrorCode 提取它所属的 domain 前缀。
 *
 * @example
 * getErrorDomain(ErrorCode.AUTH_TOKEN_EXPIRED) // 'AUTH'
 * getErrorDomain(ErrorCode.SYSTEM_UNKNOWN)      // 'SYSTEM'
 */
export function getErrorDomain(code: ErrorCode): ErrorCodeDomain {
  for (const domain of ERROR_CODE_DOMAINS) {
    if (code.startsWith(`${domain}_`) || code === domain) return domain;
  }
  return 'SYSTEM';
}

/**
 * 判断错误码是否属于 401 "需要重新登录" 族。
 * 前端拦截器看到这类 code 应触发自动退出登录流程（清 token + 跳 login 页）。
 */
export function isAuthRejection(code: ErrorCode): boolean {
  return (
    code === ErrorCode.AUTH_UNAUTHENTICATED ||
    code === ErrorCode.AUTH_TOKEN_EXPIRED ||
    code === ErrorCode.AUTH_TOKEN_INVALID ||
    code === ErrorCode.AUTH_TOKEN_REVOKED ||
    code === ErrorCode.AUTH_SESSION_INVALID
  );
}
